export interface WorkerProfile {
  id: string;
  full_name: string;
  email: string;
  phone: string;
  location: string;
  city: string;
  state: string;
  zip: string;
  worker_type: 'employee' | 'contractor' | 'freelancer' | 'gig' | 'union' | 'vendor' | 'intern' | 'part_time' | 'full_time' | 'seasonal';
  headline: string;
  bio: string;
  avatar_url: string;
  industries: string[];
  primary_trade: string;
  years_experience: number;
  hourly_rate: number;
  day_rate: number;
  salary_target: number;
  rate_currency: string;
  availability_status: 'available' | 'busy' | 'open_to_offers' | 'unavailable' | 'on_leave';
  available_from: string;
  preferred_schedule: string;
  remote_ok: boolean;
  travel_ok: boolean;
  travel_radius_miles: number;
  linkedin_url: string;
  portfolio_url: string;
  resume_url: string;
  status: 'active' | 'inactive' | 'suspended' | 'pending';
  rating_avg: number;
  rating_count: number;
  jobs_completed: number;
  union_member: boolean;
  union_id: string;
  tags: string[];
  notes: string;
  created_at: string;
  updated_at: string;
}
